### ISSUE TITLE
Abrir links externos em nova janela

### ISSUE THREAD

**Issue by pablohirafuji** [jeovazero/jeovazero.github.io#1]
Acho que seria uma melhor experiência se os links sociais (Telegram, GitHub, linkedIn...) abrissem em uma nova janela (`target="_blank"`)

**Comment by jeovazero** [comment]
Valeu pela sugestão, adicionado em [b358f85](https://github.com/jeovazero/jeovazero.github.io/commit/b358f85e9e93120484c9adfc8fe09091ee76cae4)
